-- migration: create categories table
-- description: creates the categories dictionary table for recipe categorization
-- tables affected: categories
-- dependencies: none
-- note: this is a dictionary table that will be seeded with predefined values

-- create categories table as a dictionary/lookup table
create table if not exists public.categories (
    -- auto-incrementing primary key
    id bigint primary key generated by default as identity,
    
    -- category name must be unique and not null (e.g. "Obiad", "Deser")
    name text not null unique,
    
    -- timestamp for record creation
    created_at timestamptz not null default now()
);

-- enable row level security on categories table
alter table public.categories enable row level security;

-- rls policy: allow anonymous users to select categories
-- categories are read-only dictionary data, accessible to all users
create policy "anonymous users can select categories"
    on public.categories
    for select
    to anon
    using (true);

-- rls policy: allow authenticated users to select categories
-- categories are read-only dictionary data, accessible to all users
create policy "authenticated users can select categories"
    on public.categories
    for select
    to authenticated
    using (true);

-- note: no insert/update/delete policies for regular users
-- categories should only be managed through migrations or by administrators

-- add comments to table for documentation
comment on table public.categories is 'dictionary table for recipe categories, seeded with predefined values';
comment on column public.categories.id is 'unique category identifier';
comment on column public.categories.name is 'category name, must be unique';
comment on column public.categories.created_at is 'timestamp when category was created';

