-- migration: create tags table
-- description: creates tags table for user-defined recipe tags
-- tables affected: tags
-- dependencies: auth.users
-- note: tags are unique per user (case-insensitive)

-- create tags table to store user-defined tags
create table if not exists public.tags (
    -- auto-incrementing primary key
    id bigint primary key generated by default as identity,
    
    -- foreign key to auth.users with default value from auth context
    -- tags are owned by users
    user_id uuid not null references auth.users(id) default auth.uid(),
    
    -- tag name with length validation (1-50 characters)
    name text not null check (char_length(name) > 0 and char_length(name) <= 50),
    
    -- timestamp for record creation
    created_at timestamptz not null default now()
);

-- unique index: each user can have each tag name only once (case-insensitive)
-- this prevents duplicate tags like "Italian" and "italian" for the same user
create unique index if not exists idx_tags_user_id_name_lower
    on public.tags(user_id, lower(name));

-- enable row level security on tags table
alter table public.tags enable row level security;

-- rls policy: authenticated users can select their own tags
create policy "authenticated users can select own tags"
    on public.tags
    for select
    to authenticated
    using (auth.uid() = user_id);

-- rls policy: authenticated users can insert their own tags
-- user_id must match authenticated user
create policy "authenticated users can insert own tags"
    on public.tags
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can update their own tags
-- both the current owner and new owner must be the authenticated user
create policy "authenticated users can update own tags"
    on public.tags
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can delete their own tags
create policy "authenticated users can delete own tags"
    on public.tags
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- add comments to table for documentation
comment on table public.tags is 'stores user-defined tags for recipes, unique per user (case-insensitive)';
comment on column public.tags.id is 'unique tag identifier';
comment on column public.tags.user_id is 'tag owner, references auth.users';
comment on column public.tags.name is 'tag name, 1-50 characters, unique per user';
comment on column public.tags.created_at is 'timestamp when tag was created';

