-- migration: create collections table
-- description: creates collections table for organizing recipes into user-defined groups
-- tables affected: collections
-- dependencies: auth.users
-- note: collection names are unique per user

-- create collections table to store user-defined recipe collections
create table if not exists public.collections (
    -- auto-incrementing primary key
    id bigint primary key generated by default as identity,
    
    -- foreign key to auth.users with default value from auth context
    -- collections are owned by users
    user_id uuid not null references auth.users(id) default auth.uid(),
    
    -- collection name with length validation (1-100 characters)
    name text not null check (char_length(name) > 0 and char_length(name) <= 100),
    
    -- optional collection description
    description text,
    
    -- timestamp for record creation
    created_at timestamptz not null default now(),
    
    -- timestamp for last update (managed by trigger)
    updated_at timestamptz not null default now(),
    
    -- unique constraint: each user can have each collection name only once
    unique (user_id, name)
);

-- enable row level security on collections table
alter table public.collections enable row level security;

-- rls policy: authenticated users can select their own collections
create policy "authenticated users can select own collections"
    on public.collections
    for select
    to authenticated
    using (auth.uid() = user_id);

-- rls policy: authenticated users can insert their own collections
-- user_id must match authenticated user
create policy "authenticated users can insert own collections"
    on public.collections
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can update their own collections
-- both the current owner and new owner must be the authenticated user
create policy "authenticated users can update own collections"
    on public.collections
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can delete their own collections
create policy "authenticated users can delete own collections"
    on public.collections
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- create trigger to automatically update updated_at on collections
create trigger set_updated_at
    before update on public.collections
    for each row
    execute function public.handle_updated_at();

-- add comments to table for documentation
comment on table public.collections is 'stores user-defined collections for organizing recipes, names unique per user';
comment on column public.collections.id is 'unique collection identifier';
comment on column public.collections.user_id is 'collection owner, references auth.users';
comment on column public.collections.name is 'collection name, 1-100 characters, unique per user';
comment on column public.collections.description is 'optional collection description';
comment on column public.collections.created_at is 'timestamp when collection was created';
comment on column public.collections.updated_at is 'timestamp when collection was last updated';

