-- migration: create recipes table
-- description: creates the main recipes table with soft delete support
-- tables affected: recipes
-- dependencies: auth.users, categories
-- note: implements soft delete pattern using deleted_at column

-- create recipes table to store user recipes
create table if not exists public.recipes (
    -- auto-incrementing primary key
    id bigint primary key generated by default as identity,
    
    -- foreign key to auth.users with default value from auth context
    -- recipes are owned by users and cascade deleted when user is deleted
    user_id uuid not null references auth.users(id) default auth.uid(),
    
    -- optional foreign key to categories table
    category_id bigint references public.categories(id),
    
    -- recipe name with length validation (1-150 characters)
    name text not null check (char_length(name) > 0 and char_length(name) <= 150),
    
    -- optional recipe description
    description text,
    
    -- path to image in supabase storage (optional)
    image_path text,
    
    -- ingredients stored as jsonb array
    -- format: [{"type": "header|item", "content": "text"}]
    ingredients jsonb not null,
    
    -- preparation steps stored as jsonb array
    -- format: [{"type": "header|item", "content": "text"}]
    steps jsonb not null,
    
    -- timestamp for record creation
    created_at timestamptz not null default now(),
    
    -- timestamp for last update (managed by trigger)
    updated_at timestamptz not null default now(),
    
    -- soft delete timestamp (null = not deleted)
    -- when set, recipe is considered deleted but data remains in database
    deleted_at timestamptz
);

-- enable row level security on recipes table
alter table public.recipes enable row level security;

-- rls policy: authenticated users can select their own non-deleted recipes
-- the deleted_at check ensures soft-deleted recipes are not visible
create policy "authenticated users can select own recipes"
    on public.recipes
    for select
    to authenticated
    using (auth.uid() = user_id and deleted_at is null);

-- rls policy: authenticated users can insert their own recipes
-- user_id must match authenticated user
create policy "authenticated users can insert own recipes"
    on public.recipes
    for insert
    to authenticated
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can update their own recipes
-- both the current owner and new owner (if user_id changes) must be the authenticated user
create policy "authenticated users can update own recipes"
    on public.recipes
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- rls policy: authenticated users can delete their own recipes
-- note: this allows hard delete, but app should use soft delete (set deleted_at)
create policy "authenticated users can delete own recipes"
    on public.recipes
    for delete
    to authenticated
    using (auth.uid() = user_id);

-- create trigger to automatically update updated_at on recipes
create trigger set_updated_at
    before update on public.recipes
    for each row
    execute function public.handle_updated_at();

-- add comments to table for documentation
comment on table public.recipes is 'stores user recipes with soft delete support';
comment on column public.recipes.id is 'unique recipe identifier';
comment on column public.recipes.user_id is 'recipe owner, references auth.users';
comment on column public.recipes.category_id is 'optional category, references categories';
comment on column public.recipes.name is 'recipe name, 1-150 characters';
comment on column public.recipes.description is 'optional recipe description';
comment on column public.recipes.image_path is 'path to image in supabase storage';
comment on column public.recipes.ingredients is 'ingredients as jsonb array with type and content';
comment on column public.recipes.steps is 'preparation steps as jsonb array with type and content';
comment on column public.recipes.created_at is 'timestamp when recipe was created';
comment on column public.recipes.updated_at is 'timestamp when recipe was last updated';
comment on column public.recipes.deleted_at is 'soft delete timestamp, null means not deleted';

